services:
  - type: web
    name: pdf-toolbox
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt gunicorn
    startCommand: gunicorn -c gunicorn_conf.py wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: WEB_CONCURRENCY
        value: "1"
      - key: WEB_THREADS
        value: "8"
